# version: "3.8"

services:
  # API Gateway
  gateway:
    image: express-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
      - "9876:9876" # Admin API
    volumes:
      - ./gateway/gateway.config.yml:/var/lib/eg/gateway.config.yml
      - ./gateway/system.config.yml:/var/lib/eg/system.config.yml
    networks:
      - microservices-network
    depends_on:
      - service-a
      - service-b

  # Microservice A
  service-a:
    build:
      context: ./services/service-a
      dockerfile: Dockerfile
    container_name: service-a
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SERVICE_NAME=Service-A
    networks:
      - microservices-network

  # Microservice B
  service-b:
    build:
      context: ./services/service-b
      dockerfile: Dockerfile
    container_name: service-b
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - SERVICE_NAME=Service-B
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
